version: 1.0.0
requires:
  fbl: '>=0.4.3'
  applications:
   - yarn

pipeline:
  '--':
    - ctx:
        '$':
          inline:
            fbl: 0.4.3

    - prompt:
        message: 'What is the name of the plugin?'
        default: <%- $.require('path').basename(cwd) %>
        assignResponseTo:
          ctx: $.name
        schema:
          type: string
          maxLength: 214
          minLength: 1
          pattern: "^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$"

    - prompt:
        message: 'What license you want to use?'
        default: MIT
        assignResponseTo:
          ctx: $.license

    - prompt:
        message: 'Where you want to store it?'
        default: <%- cwd %>
        assignResponseTo:
          ctx: $.destination

    - prompt:
        message: 'Who is the author?'
        assignResponseTo:
          ctx: $.author

    - '||':
        <$ [
          'src',
          'test',
          '.gitignore',
          '.npmignore',
          'index.ts',
          'tsconfig.json',
          'tslint.json'
        ].forEach(path => { $>
        - cp:
            from: templates/<$- path $>
            to: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/
        <$ }); $>

        <$ [
          'LICENSE',
          'package.json'
        ].forEach(path => { $>
        - '->':
            contentFromFile: templates/<$- path $>
            path: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/<$- path $>
        <$ }); $>

    - exec:
        command: yarn
        args:
          - install