version: 1.0.0
requires:
  fbl: '>=1.7.1'
  applications:
   - yarn

pipeline:
  '--':
    - ctx:
        '$':
          inline:
            fbl: 
              current: '1.7.1'
              range: '>=1.7.1 <2.0.0' 

    <$ if (!ctx.name) { $>
    - prompt:
        message: 'Plugin name:'
        default: <%- $.require('path').basename(cwd) %>
        assignResponseTo:
          ctx: $.name
        schema:
          type: string
          maxLength: 214
          minLength: 1
          pattern: "^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$"
    <$ } $>

    <$ if (!ctx.license) { $>
    - prompt:
        message: 'License:'
        default: MIT
        assignResponseTo:
          ctx: $.license
    <$ } $>

    <$ if (!ctx.destination) { $>
    - prompt:
        message: 'Location:'
        default: <%- cwd %>
        assignResponseTo:
          ctx: $.destination
    <$ } $>

    <$ if (!ctx.author) { $>
    - prompt:
        message: 'Author:'
        assignResponseTo:
          ctx: $.author
    <$ } $>

    - '||':
        <$ [
          'src',
          'test',
          '.commitlintrc.yml',
          '.czrc',
          '.editorconfig',
          '.gitignore',
          '.huskyrc.yml',
          '.lintstagedrc.yml',
          '.mocharc.yml',
          '.npmignore',
          '.prettierignore',
          '.prettierrc.yml',
          'index.ts',
          'tsconfig.json',
          'tslint.json'
        ].forEach(path => { $>
        - cp:
            from: templates/<$- path $>
            to: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/
        <$ }); $>

        <$ [
          'LICENSE',
          'package.json'
        ].forEach(path => { $>
        - '->':
            contentFromFile: templates/<$- path $>
            path: <%- $.fs.getAbsolutePath(ctx.destination, cwd) %>/<$- path $>
        <$ }); $>

    - exec:
        command: yarn
        args:
          - install
        wd: <%- ctx.destination %>
        options:
          verbose: true